# Generated by Django 5.2.1 on 2025-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechParkParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(unique=True)),
                ("join_date", models.DateField()),
                ("end_date", models.DateField()),
                ("bin", models.BigIntegerField()),
                ("status", models.BooleanField(default=True)),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
    ]
